---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ecom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-ecom-app
  template:
    metadata:
      labels:
        app: demo-ecom-app
    spec:
      containers:
      - name: demo-ecom-app
        image: sarveshanand94/ecomdb:v2
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: "3"
            memory: 3000Mi
          requests:
            cpu: "1"
            memory: 1000Mi
        env:
          - name: DB_NAME
            value: "<your-db-name>"  # e.g., evershop
          - name: DB_USER
            value: "<your-db-user>"
          - name: DB_PASSWORD
            value: "<add passoword>" # e.g - Mypassword!123
          - name: DB_HOST # Very Imporatant - Add DBO K8S service endpoint
            value: "<DBO Proxy Endpoint>" # e.g - dbo-demo-postgres-my-8e88b.castai-db-optimizer.svc.cluster.local
          - name: DB_PORT
            value: "5432"
          - name: DB_SSLMODE
            value: "no-verify"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-ecom-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # Set to "true" for internal-only access
spec:
  selector:
    app: demo-ecom-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer  # Publicly exposes the service. Use ClusterIP for internal-only access.
