apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-2
  version: "1.29"  
  tags:
    persist: "true"

nodeGroups:
  - name: ng-medium
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 3
    tags:
      persist: "true"
